apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "salesken-app.fullname" . }}-nginx-config
  labels:
    {{- include "salesken-app.labels" . | nindent 4 }}
data:
  nginx.conf: |
    server {
      listen 80;
      location / {
        proxy_pass http://{{ include "salesken-app.fullname" . }}:{{ .Values.service.port }};
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
      }
    }
