apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "salesken-app.fullname" . }}-nginx
  labels:
    {{- include "salesken-app.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "salesken-app.fullname" . }}-nginx
  template:
    metadata:
      labels:
        app: {{ include "salesken-app.fullname" . }}-nginx
    spec:
      containers:
        - name: nginx
          image: {{ .Values.nginx.image }}
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
      volumes:
        - name: nginx-config
          configMap:
            name: {{ include "salesken-app.fullname" . }}-nginx-config
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "salesken-app.fullname" . }}-nginx
  labels:
    {{- include "salesken-app.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: {{ include "salesken-app.fullname" . }}-nginx
